[package]
name = "vigenere"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30.1", features = ["socket", "signal", "net"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
libc = "0.2.176"
